### ISSUE TITLE
1repo 1pod？

### ISSUE THREAD

**Issue by bboysoulcn** [caldito/soup#12]

**Comment by bboysoulcn** [comment]
If I want to deploy two repo's，Do I need to deploy two pods？

**Comment by caldito** [comment]
Yes, right now the approach is 1 repo 1 pod. Handling multiple repositories is a thing that I might implement in the future. Would you consider it very useful for your use case?

It might cause some overlap on the mapping between branches and namespaces, that is why I'm hesitant on doing it.

**Comment by bboysoulcn** [comment]
> Yes, right now the approach is 1 repo 1 pod. Handling multiple repositories is a thing that I might implement in the future. Would you consider it very useful for your use case?
> 
> It might cause some overlap on the mapping between branches and namespaces, that is why I'm hesitant on doing it.

I think 1 repo 1pod is the best solution.
Focused on design and usage simplicity.
