### ISSUE TITLE
want arm64 support

### ISSUE THREAD

**Issue by bboysoulcn** [caldito/soup#13]
this is a simple gitops tool

I want to run it on my raspberry pi cluster

I hope it can support arm64

thanks bro

**Comment by caldito** [comment]
Hey!

Sure, it makes sense and seems easy to do. Will add it to the next release.

Any other suggestion feel free to open an issue or submit a pull request :)

**Comment by bboysoulcn** [comment]
> Hey!
> 
> Sure, it makes sense and seems easy to do. Will add it to the next release.
> 
> Any other suggestion feel free to open an issue or submit a pull request :)

tk bro

**Comment by caldito** [comment]
@bboysoulcn I'll close it when ready

**Comment by caldito** [comment]
Now you have arm64 support with the new release [v0.4.0](https://github.com/caldito/soup/releases/tag/v0.4.0) @bboysoulcn , so I'm closing the issue

**Comment by bboysoulcn** [comment]
tk bro
